### ISSUE TITLE
[inference_class] Get a pyro-engine inference class working on raspi with latest vision features

### ISSUE THREAD

**Issue by chloeskt** [pyronear/pyro-engine#14]
## 🚀 Feature

Hello all ! As we are engaging into a test phase, it would be great to have a ready-to-deploy application (as a python class) which would make the inference (given the path to an image) and output the score (0 - 1).

## Motivation

Right now, our setup is the following:
- 4 rpi with camera which send pictures to a "main rpi" (the 5th) using local network
- on a shared folder based on the main rpi, the latter does the inference on each picture (might be smart to do it on a batch of pictures if possible, but otherwise it will do it one by one)
- therefore, the pyro-engine must, given the path to the image or paths to the batch of images, do the inference with the latest vision model 

This is this last step that we need so that we can make all the other features around (get the shared folder ready and get the system to send an alert to the API, this will be discussed with the api team on pyro-api). 
Then, we might put all this last step (sending the alert to the API with right format) into the pyro-engine repo.

I'd be happy to help with anything related to this issue and discuss it in further depth ! 🤗

**Comment by frgfm** [comment]
Hey there @chloeskt :wave: 

Question about your setup suggestion: if we are to send pictures between RPi, we can send only the decoded bytes rather than saving the image, can't we?

I would rather suggest that:
- each rpi connected to a camera saves on its disk the media from the camera.
- at the same time, it sends the decoded bytes to the main RPI for analysis
- if it answers that there is a wildfire --> the origin RPI sends an alert through the API
- if not, it does nothing
- assuming we set a cache size, we would gradually delete the oldest saved images to avoid burning through the whole hard disk memory

What do you think?

**Comment by chloeskt** [comment]
Hi @frgfm,

Thanks for you reply,

Yes I guess we can send only the decoded bytes. Don't know how to do that, but I will check it up. 

To answer your comments: 
- each pi with camera already save on its disk the image in this setup
- will need to check how to send the decoded bytes
- yes the main rpi sends the alert to rpi if need be
- yes in this setup we found about a mechanism to delete older images on the SD card (the details of that mechanism still have not been discussed but will be soon). Did not think about a cache though, I'll have to check that !

**Comment by frgfm** [comment]
No worries about the decoded bytes, happy to implement it. The only thing is now: how do we send it over to the other raspberry pi?
Is it exposed on a specific port? over the general internet? what's the process for information transfer? (it will have to answer back anyway)

For the cache, we could alternative use a simple python queue of which we limit the size. Each time an element is popped, we delete the content file :man_shrugging:

**Comment by chloeskt** [comment]
Yes I think a python queue is way easier ! 

The transfer of images is still in discussion on our end. I used a simple rsync on my end for the tests I've done. For instance the script used was: https://github.com/pyronear/pyro-sys-setup/blob/master/scripts/take_picture.py

**Comment by frgfm** [comment]
Oh I see rsync would require files saved to hard disk, now I understand your earlier suggestion. My thoughts on this:
- if we transfer files, the inference device will have to constantly check for new files in a folder (perhaps it's easier than I imagine but I tend to think that it will require more load than needed)
- if we transfer bytes, the main raspberry runs like a web server accepting analysis request. So any request that arrives will get a response.

A FastAPI server with a single analysis route on the inference device would do the job! Let me know what you think

**Comment by chloeskt** [comment]
Yes, yesterday we briefly mentioned that we could use our main rpi as a webserver. As I said, everything is still in discussion, I was going to explore all our options this week-end. 

The `take_picture.py` script is only a "toy" script, I used rsync only to show that we could easily send files to the main rpi using ssh. Yesterday I raised the point of finding smarter options, we still need to investigate that ! 

If you have good resources on FastAPI to recommend, I'm very interested ! This could save me some precious time. Also if you already have a clear idea of what needs to be done, feel free to tell us. It seems to be an option 👍 and we can easily deploy it onto the main rpi using Ansible; does not seems complicated.

I will investigate the question of how to transfer images in depth over the week-end 🤗

**Comment by frgfm** [comment]
@chloeskt regarding the FastAPI option, happy to show you around in the incoming PRs, but for efficiency sake, the implementation will fall on the @pyronear/back-end team's responsibility :)
You guys in @pyronear/hardware already have a lot to deal with haha

**Comment by chloeskt** [comment]
As you wish ! Maybe, I would suggest that we step up a quick call between the two teams, so that you can present the pros and cons of this solution (implement the FastAPI solution), so that we can decide whether to adopt it or not (Spoiler alert, we probably will, but still I believe that we should discuss it a bit). What you do think ?
