### ISSUE TITLE
Workaround for the mysterious Docker failure

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#146]
We experience on our devices that the docker stops working, i.e. the docker is still running, is active, but nothing happens (no inference, no api interactions etc) 

Until now, since this bug has no root cause and appears after a random runtime, we have no robust solution. 

On the other hand, a simple docker stop, docker up (@MateoLostanlen if could explicit the exact commands   ), bring us back to the expected docker behavior. 

Therefore, in order to keep the main functionalities of our product, until we have a long-lasting solution, I suggest to implement a workaround as for example, to regularly execute the actions that lead us to review the correct functioning. 

Happy to discuss it !

**Comment by MateoLostanlen** [comment]
solved by #153
