### ISSUE TITLE
No Night's Watch

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#26]
## 🚀 Feature

Within the scope of our MVP, we do not provide smoke detection at night. It has to be handled.

#### Night time period 

First, we need to define a time range that corresponds to night.
The length of daylight is not the same for each link and changes throughout the year (good job Sherlock).

<u>Suggestion</u>: considering that the MVP takes place in France, in Ardeche, during the summer only, we can consider a fixed time range for the night period. For example from 10pm-5am (French time)?  What do you think ? 

The storage place of these fields is also to be defined.

#### Management of alerts / inference / photo taking: 

If it is a priori rather simple to imagine just not to bring up alerts on the front on the night time range, it is important to preserve our resources and avoid unnecessary calculations. 

Hence, either pi cameras do not take picture at night, or, the inference/alerting workflow does nothing at night, etc 

Not taking picture at night seems to be a suitable solution. Therefore, pi cameras need to be on time (not being connected to the internet, and not having an internal clock, they are by default not on time). Fortunately pi cameras have the possibility to access the current time through the web server. 

- Either, a GTC clock is added to the pi camera and its ensure to be on time by pinging frequently the webserver. Hence, the pi camera check if the current time is  in the night range, before taking picture. 

- Either, the pi camera can ask the webserver what time is it,  before taking a picture andsending it for inference. 

There are quite various other implementation solution. What do you think ? 

Happy to discuss it !

**Comment by frgfm** [comment]
Not 100% sure @fe51 but we can close this right?
cf. https://github.com/pyronear/pyro-engine/pull/57#issuecomment-884942890

**Comment by fe51** [comment]
Yes, this issue is quite old and irrelevant now, so we can close it !

However, I am not totally convinced about the actual solution : inference still performed at night for nothing (as long as the process is not so intensive why not), and managing day alerts frontside with a dependency to an external api, i am not sure this is robust enough. That being said, I have not checked if there was issues about with the availability of this api !
