### ISSUE TITLE
Image and alert do not identify device / camera

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyro-engine#37]
## 🐛 Bug

Unless I am mistaken there is nothing that identifies the actual device / camera that sends the image which triggers the alert.

If I understand the logic, each device with a camera will have a [runner](https://github.com/pyronear/pyro-engine/blob/44f0a0791f2873be60204359dd9028a580c7f712/pyroengine/pi_utils/runner.py) that sends an image to the main RPI via the local webserver using the [inference](https://github.com/pyronear/pyro-engine/blob/44f0a0791f2873be60204359dd9028a580c7f712/server/src/app/api/routes/inference.py#L27) route.  

The image is then processed in the main PRI and, if needed, an [alert is sent](https://github.com/pyronear/pyro-engine/blob/49d9ae75c3d128770b2ee57892409606b9426132/pyroengine/engine/engine.py#L50) using the event ID. But the information about the original camera is lost as far as I can see.

**Comment by fe51** [comment]
Hello Bruno !

There is no identification so far, but PR #31 adding security adds an authentication layer, hence, it will fix this point !

**Comment by frgfm** [comment]
This was closed by #50
