### ISSUE TITLE
Impossible to reach webserver once built

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#44]
Thanks to the previous #42, the webserver builds successfully on Rpi.
However, it seems not possible to reach it (either localy or from another machine on the network)

I receive the following error ``curl: (56) Recv failure: Connection reset by peer  `when doing a curl http://localhost:8002/docs`to reach the documentaion. 

Having no time to investigate further, I am opening this issue, hoping that this just an oversight from my side and it will quickly closed :) 

Thanks a lot

**Comment by MateoLostanlen** [comment]
@fe51 this is just à PORT issue I will fix this today 😉

**Comment by fe51** [comment]
I had this port mapping issue in mind! Coool :)
