### ISSUE TITLE
webserver docker image available for common arch

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#45]
To date, the docker image of pyro-engine available on [docker hub](https://hub.docker.com/r/pyronear/pyro-engine) is only for linux/arm architecture.

It would be nice to be able to run it form our computers (Maybe I am mistaking and this is already okay on common machines arch)

Hence, it would be easier to develop and test on our computer and set up github workflows tests

Happy to discuss it, 

Thanks a lot

**Comment by MateoLostanlen** [comment]
Done : https://hub.docker.com/r/pyronear/pyro-engine/tags?page=1&ordering=last_updated

**Comment by fe51** [comment]
Great :)

Thank you @MateoLostanlen !
