### ISSUE TITLE
Codecov fail

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-engine#48]
## 🐛 Bug

Codecov doesn't seem to be very stable. We already made a similar change in the [past](https://github.com/pyronear/pyro-vision/pull/83/files), after v1.0.6 now v1 doesn't work anymore (#47). Changing the version to v1.0.5 [seems ](#49) to solve the problem

@frgfm what do you thiink ?

**Comment by frgfm** [comment]
Can you edit & correct the hyperlink you wanted to put in "seems"? The URL brings back to this very page, so I can't answer your question :sweat_smile:

**Comment by MateoLostanlen** [comment]
sorry for that, it was suppose to bring you to #49, but at the end It's not working :/

**Comment by MateoLostanlen** [comment]
Ok the bug comes from me, I push from my pro pc on which there is another github account, my commit was not marked verified so codcove refuses authentication
