### ISSUE TITLE
Add Rapberry Pi tests

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-engine#5]
## 🚀 Feature
We need to create a test environment for rapsberry pi using a docker. It is important that these tests are part of the CI

**Comment by frgfm** [comment]
Big issue so far: docker will not be able to create an ARM environment on common architectures :/
I haven't found my way around that so far...

**Comment by MateoLostanlen** [comment]
Damn... I just red your comment, i'm trying for 2 days haha

**Comment by MateoLostanlen** [comment]
@frgfm maybe we can try this : https://dev.to/l04db4l4nc3r/self-hosted-github-actions-using-raspberry-pi-212m

And testing raspberry specific features only for release. What do you think ?

**Comment by MateoLostanlen** [comment]
Just found this, fake raspberry package https://pypi.org/project/fake-rpi/

**Comment by frgfm** [comment]
@MateoLostanlen Regarding self hosting, I thought about this, but apart from having a dedicated Raspberry pi connected to the internet which would run all the CI, I don't see how we could managed it :/

I'll look into the fake raspberry package :ok_hand:

**Comment by MateoLostanlen** [comment]
If it's Work the fake package might be a good solution. If not, we could buy a dedicated pi (maybe a pizero)
